{% set name = "pyogrio" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geopandas/pyogrio/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ae87170d6cb3d662eaddcf147b2c8be3120dfe99835e418caef2e4fdaa825c81

build:
  number: 0
  skip: true  # [py<38 or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - libgdal
    - versioneer
    - tomli # [py<311]
  run:
    - python
    - gdal
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyogrio

about:
  home: https://github.com/geopandas/pyogrio/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Vectorized vector I/O using GDAL
  description: |
    Provide faster I/O using GDAL OGR to read / write vector geospatial files.
    Intended for use with libraries that consume WKB for their internal
    constructs, such as pygeos.
  doc_url: https://pyogrio.readthedocs.io/
  dev_url: https://github.com/geopandas/pyogrio

extra:
  recipe-maintainers:
    - brendan-ward
    - jorisvandenbossche
    - martinfleis
