{% set name = "pyogrio" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geopandas/pyogrio/releases/download/v{{ version }}/pyogrio-{{ version }}.tar.gz
  sha256: 6a6fa2e8cf95b3d4a7c0fac48bce6e5037579e28d3eb33b53349d6e11f15e5a8

build:
  number: 1
  skip: true  # [py<38 or python_impl == 'pypy' or ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - gdal
    - versioneer
    - tomli  # [py<311]
  run:
    - python
    - gdal
    - packaging
    - numpy

test:
  imports:
    - pyogrio

about:
  home: https://github.com/geopandas/pyogrio/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Vectorized vector I/O using GDAL
  description: |
    Provide faster I/O using GDAL OGR to read / write vector geospatial files.
    Intended for use with libraries that consume WKB for their internal
    constructs, such as pygeos.
  doc_url: https://pyogrio.readthedocs.io/
  dev_url: https://github.com/geopandas/pyogrio

extra:
  recipe-maintainers:
    - brendan-ward
    - jorisvandenbossche
    - martinfleis
