{% set name = "pyogrio" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geopandas/pyogrio/releases/download/v{{ version }}/pyogrio-{{ version }}.tar.gz
  sha256: 459ec590c3c1cda451f3f73c88a678c32b127de783bf54c41ea6ad708969f020

build:
  number: 0
  skip: true  # [py<38 or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - libgdal
    - versioneer
    - tomli  # [py<311]
  run:
    - python
    - gdal
    - packaging
    - numpy

test:
  imports:
    - pyogrio

about:
  home: https://github.com/geopandas/pyogrio/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Vectorized vector I/O using GDAL
  description: |
    Provide faster I/O using GDAL OGR to read / write vector geospatial files.
    Intended for use with libraries that consume WKB for their internal
    constructs, such as pygeos.
  doc_url: https://pyogrio.readthedocs.io/
  dev_url: https://github.com/geopandas/pyogrio

extra:
  recipe-maintainers:
    - brendan-ward
    - jorisvandenbossche
    - martinfleis
